name: Deploy Python project to Azure Function App

on:
  push

env:
  AZURE_FUNCTIONAPP_NAME: 'CB-AMEX'  
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'             

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: List files to be zipped
      run: ls -laR

    - name: Zip the application for deployment
      run: |
        zip -r release.zip . -x "*.git*" -x ".github/*" -x "*.python_packages/*" -x "venv/*"

    - name: List zip
      run: |
        ls -la
        unzip -l release.zip

    - name: Upload ZIP as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: functionapp-artifact
        path: release.zip

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: functionapp-artifact

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: "./release.zip"
        scm-do-build-during-deployment: true
        enable-oryx-build: true
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0EC64C07241C4B13BE7F59446D787CF5 }}
