name: Deploy Python project to Azure Function App

on:
  push

env:
  AZURE_FUNCTIONAPP_NAME: 'CB-AMEX'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
    - name: Zip the function app
      run: zip -r functionapp.zip . -x '*.git*' -x '.*' -x 'python_packages/*'
    - uses: actions/upload-artifact@v3
      with:
        name: functionapp
        path: functionapp.zip

  deploy:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: functionapp
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: functionapp.zip
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0EC64C07241C4B13BE7F59446D787CF5 }}
