name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'CB-AMEX'  
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'             

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

        #- name: Create and start virtual environment
        #run: |
        #python -m venv venv
        #source venv/bin/activate

    - name: Install dependencies
      shell: bash
      run: |
        pushd './.'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        pip install azure-functions --no-cache-dir
        pip list
        popd
        pwd

    - run: |
        python function_app.py 
        pwd

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: List files to be zipped
      run: ls -la

    - name: Zip the application for deployment
      run: |
        zip -r release.zip . -x "*.git*" -x ".github/*" -x "*.python_packages/*" -x "venv/*"

    - name: List and Check the size of the zip
      run: |
        ls -lh release.zip
        unzip -l release.zip

    - name: Upload ZIP as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: functionapp-artifact
        path: |
          ./release.zip
          !venv/

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: functionapp-artifact

    - name: List Release.zip
      run: |
        ls -la
        unzip -l ./release.zip

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: release.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: false
        enable-oryx-build: true
